#region copyright
/**
 * Joint Copyright (c) 2012 Miguel A. Ramos, Eddy Jimenez 
 * (mramosr85@gmail.com)
 *
 * This file is part of OfficeGengoAddins.
 *
 * OfficeGengoAddins is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OfficeGengoAddins is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with OfficeGengoAddins.  If not, see <http://www.gnu.org/licenses/>.
 */
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGengoTranslator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyGengoTranslator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //EM Solutions//{0}//.
        /// </summary>
        internal static string AppDirectory {
            get {
                return ResourceManager.GetString("AppDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Free!.
        /// </summary>
        internal static string BtnTierMachine {
            get {
                return ResourceManager.GetString("BtnTierMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        internal static string BtnTierProfessional {
            get {
                return ResourceManager.GetString("BtnTierProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string BtnTierStardard {
            get {
                return ResourceManager.GetString("BtnTierStardard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra.
        /// </summary>
        internal static string BtnTierUltra {
            get {
                return ResourceManager.GetString("BtnTierUltra", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap captcha {
            get {
                object obj = ResourceManager.GetObject("captcha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in application.
        /// </summary>
        internal static string ErrorAppMessage {
            get {
                return ResourceManager.GetString("ErrorAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrapper error.
        /// </summary>
        internal static string ErrorInitializinClientWrapper {
            get {
                return ResourceManager.GetString("ErrorInitializinClientWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB {
            get {
                return ResourceManager.GetString("JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string JOB_REJECT_FOLLOWUP_CANCEL {
            get {
                return ResourceManager.GetString("JOB_REJECT_FOLLOWUP_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requeue.
        /// </summary>
        internal static string JOB_REJECT_FOLLOWUP_REQUEUE {
            get {
                return ResourceManager.GetString("JOB_REJECT_FOLLOWUP_REQUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incomplete.
        /// </summary>
        internal static string JOB_REJECT_REASON_INCOMPLETE {
            get {
                return ResourceManager.GetString("JOB_REJECT_REASON_INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        internal static string JOB_REJECT_REASON_OTHER {
            get {
                return ResourceManager.GetString("JOB_REJECT_REASON_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quality.
        /// </summary>
        internal static string JOB_REJECT_REASON_QUALITY {
            get {
                return ResourceManager.GetString("JOB_REJECT_REASON_QUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string JOB_STATUS_APPROVED_FRIENDLY {
            get {
                return ResourceManager.GetString("JOB_STATUS_APPROVED_FRIENDLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting{0}translator.
        /// </summary>
        internal static string JOB_STATUS_AVAILABLE_FRIENDLY {
            get {
                return ResourceManager.GetString("JOB_STATUS_AVAILABLE_FRIENDLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string JOB_STATUS_CANCELLED_FRIENDLY {
            get {
                return ResourceManager.GetString("JOB_STATUS_CANCELLED_FRIENDLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected,{0}Pending{0}Review.
        /// </summary>
        internal static string JOB_STATUS_HELD_FRIENDLY {
            get {
                return ResourceManager.GetString("JOB_STATUS_HELD_FRIENDLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating.
        /// </summary>
        internal static string JOB_STATUS_PENDING_FRIENDLY {
            get {
                return ResourceManager.GetString("JOB_STATUS_PENDING_FRIENDLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewable.
        /// </summary>
        internal static string JOB_STATUS_REVIEWABLE_FRIENDLY {
            get {
                return ResourceManager.GetString("JOB_STATUS_REVIEWABLE_FRIENDLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revising.
        /// </summary>
        internal static string JOB_STATUS_REVISING_FRIENDLY {
            get {
                return ResourceManager.GetString("JOB_STATUS_REVISING_FRIENDLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://mygengo.com/express/account/api_settings/.
        /// </summary>
        internal static string LINK_GET_YOUR_KEYS {
            get {
                return ResourceManager.GetString("LINK_GET_YOUR_KEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://mygengo.com/help/quality_policy.
        /// </summary>
        internal static string LINK_WHAT_MEAN_TIERS {
            get {
                return ResourceManager.GetString("LINK_WHAT_MEAN_TIERS", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap loading_balls {
            get {
                object obj = ResourceManager.GetObject("loading_balls", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login OK..
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string LogOf {
            get {
                return ResourceManager.GetString("LogOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off OK.
        /// </summary>
        internal static string LogOfSuccess {
            get {
                return ResourceManager.GetString("LogOfSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap machine_mini {
            get {
                object obj = ResourceManager.GetObject("machine_mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap monitor {
            get {
                object obj = ResourceManager.GetObject("monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mygengo_machine_medium {
            get {
                object obj = ResourceManager.GetObject("mygengo_machine_medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mygengo_powered {
            get {
                object obj = ResourceManager.GetObject("mygengo_powered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mygengo_pro_medium {
            get {
                object obj = ResourceManager.GetObject("mygengo_pro_medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mygengo_standard_medium {
            get {
                object obj = ResourceManager.GetObject("mygengo_standard_medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mygengo_ultra_medium {
            get {
                object obj = ResourceManager.GetObject("mygengo_ultra_medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation approved OK.
        /// </summary>
        internal static string TEXT_INFO_APPROVED_OK {
            get {
                return ResourceManager.GetString("TEXT_INFO_APPROVED_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation cancelled OK.
        /// </summary>
        internal static string TEXT_INFO_CANCEL_OK {
            get {
                return ResourceManager.GetString("TEXT_INFO_CANCEL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order posted OK.
        /// </summary>
        internal static string TEXT_INFO_ORDER_OK {
            get {
                return ResourceManager.GetString("TEXT_INFO_ORDER_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data refreshed OK.
        /// </summary>
        internal static string TEXT_INFO_REFRESH_OK {
            get {
                return ResourceManager.GetString("TEXT_INFO_REFRESH_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation rejected OK.
        /// </summary>
        internal static string TEXT_INFO_REJECT_OK {
            get {
                return ResourceManager.GetString("TEXT_INFO_REJECT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction requested OK.
        /// </summary>
        internal static string TEXT_INFO_REQCORRECTION_OK {
            get {
                return ResourceManager.GetString("TEXT_INFO_REQCORRECTION_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation loaded OK.
        /// </summary>
        internal static string TEXT_INFO_REVIEW_OK {
            get {
                return ResourceManager.GetString("TEXT_INFO_REVIEW_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation loaded OK.
        /// </summary>
        internal static string TEXT_INFO_VIEW_OK {
            get {
                return ResourceManager.GetString("TEXT_INFO_VIEW_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to machine.
        /// </summary>
        internal static string TIER_MACHINE {
            get {
                return ResourceManager.GetString("TIER_MACHINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pro.
        /// </summary>
        internal static string TIER_PROFESSIONAL {
            get {
                return ResourceManager.GetString("TIER_PROFESSIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard.
        /// </summary>
        internal static string TIER_STANDARD {
            get {
                return ResourceManager.GetString("TIER_STANDARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ultra.
        /// </summary>
        internal static string TIER_ULTRA {
            get {
                return ResourceManager.GetString("TIER_ULTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ultra_proofread.
        /// </summary>
        internal static string TIER_ULTRA_PROOFREAD {
            get {
                return ResourceManager.GetString("TIER_ULTRA_PROOFREAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to char.
        /// </summary>
        internal static string TIER_UNIT_TYPE_CHAR {
            get {
                return ResourceManager.GetString("TIER_UNIT_TYPE_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character.
        /// </summary>
        internal static string TIER_UNIT_TYPE_CHARACTER {
            get {
                return ResourceManager.GetString("TIER_UNIT_TYPE_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to word.
        /// </summary>
        internal static string TIER_UNIT_TYPE_WORD {
            get {
                return ResourceManager.GetString("TIER_UNIT_TYPE_WORD", resourceCulture);
            }
        }
    }
}
